from pathlib import Path

# Evolution settings
POPULATION_SIZE = 100
MAX_GENERATIONS = 2000
FITNESS_MAX_STAGNATION_GENERATIONS = 30

# Canvas settings
CANVAS_WIDTH_PX = 1920
CANVAS_HEIGHT_PX = 1080
CANVAS_ASPECT_RATIO_X= CANVAS_WIDTH_PX / max(CANVAS_WIDTH_PX, CANVAS_HEIGHT_PX)
CANVAS_ASPECT_RATIO_Y = CANVAS_HEIGHT_PX / max(CANVAS_WIDTH_PX, CANVAS_HEIGHT_PX)

# Rendering settings
OUTPUT_DIR = Path("output")
