from pathlib import Path

# Evolution settings
POPULATION_SIZE = 100
MAX_GENERATIONS = 2000
FITNESS_MAX_STAGNATION_GENERATIONS = 30

# Canvas settings
CANVAS_WIDTH = 1920
CANVAS_HEIGHT = 1080
MAX_RELATIONAL_WIDTH = min(1, CANVAS_WIDTH / CANVAS_HEIGHT)
MAX_RELATIONAL_HEIGHT = min(1, CANVAS_HEIGHT / CANVAS_WIDTH)

# Rendering settings
OUTPUT_DIR = Path("output")
