"""
A framework for User Interface generation/optimization using NSGA-III (Non-dominated Sorting Genetic Algorithm III).
Uses a predefiend set of scorers/criteria and a blueprint of the Interface to generate approximately optimal UI designs.
The generated designs will be written as HTML files in the output directory.\n

Due to the complexity of the problem the Blueprint can be devided into sub-blueprints which will be optimized separately.
The algorithm will BFS through the blueprint hierarchy and optimize each blueprint separately.
At the end the final UI will be generated by combining the optimized containers for each blueprint.
"""

import logging
import random
from argparse import ArgumentParser, RawDescriptionHelpFormatter

import numpy as np

from blueprints.ecommerce_prototype import interface_blueprint
from constants import BASE_LOGGER_NAME, OUTPUT_DIR
from optimization.nsga3 import run_nsga3_optimization
from rendering.renderer import HTMLRenderer
from scoring.constraints.min_size import MinSizeScorer
from scoring.constraints.padding import PaddingScorer
from util import container_optimization_results_to_optimized_containers

parser = ArgumentParser(
    prog="ui-nsga3",
    description=__doc__,
    formatter_class=RawDescriptionHelpFormatter,
)
parser.add_argument(
    "-g",
    "--generations",
    type=int,
    default=200,
    help="Number of generations to run optimization for",
)
parser.add_argument(
    "-p",
    "--min-pop-size",
    type=int,
    default=100,
    help="Minimum population size for optimization (will be used for reference direction generation, default: 100)",
)
parser.add_argument(
    "-s",
    "--seed",
    type=int,
    default=None,
    help="Random seed for optimization (default: None)",
)

parser.parse_args()


def setup_logger(level: str = "INFO"):
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(level)
    stream_formatter = logging.Formatter("[%(levelname)s] [%(name)s] - %(message)s")
    stream_handler.setFormatter(stream_formatter)

    logger = logging.getLogger(BASE_LOGGER_NAME)
    logger.setLevel(level)
    logger.addHandler(stream_handler)
    logger.propagate = False
    return logger


if __name__ == "__main__":
    setup_logger("DEBUG")

    # Init output dir
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    args = parser.parse_args()
    SEED = args.seed
    if SEED is not None:
        random.seed(SEED)
        np.random.seed(SEED)

    # Run optimization
    container_optimzation_results = run_nsga3_optimization(
        root_blueprint=interface_blueprint,
        n_gen=args.generations,
        min_pop_size=args.min_pop_size,
        seed=SEED,
        constraints=[
            PaddingScorer(padding=0.01),
            MinSizeScorer(min_width=0.0, min_height=0.0),
        ],
        mutation_rate=0.1,
    )

    # TODO: REMOVE
    # pickle the optimization results for later analysis
    import pickle

    pickle.dump(
        container_optimzation_results,
        open(OUTPUT_DIR / "container_optimization_results.pkl", "wb"),
    )

    # Convert to optimized containers for easier rendering
    optimized_containers = container_optimization_results_to_optimized_containers(
        container_optimzation_results
    )

    # Assemble final ui
    optimized_root_container = optimized_containers[interface_blueprint.blueprint_id]
    HTMLRenderer.write_container_to_html(
        optimized_root_container,
        OUTPUT_DIR / "final_optimized_ui.html",
        optimized_containers,
    )
