"""
A framework for User Interface generation/optimization using NSGA-III (Non-dominated Sorting Genetic Algorithm III).
Uses a predefiend set of scorers/criteria and a blueprint of the Interface to generate approximately optimal UI designs.
The generated designs will be written as HTML files in the output directory.

Due to the complexity of the problem the Blueprint can be devided into sub-blueprints which will be optimized separately.
The algorithm will BFS through the blueprint hierarchy and optimize each blueprint separately.
At the end the final UI will be generated by combining the optimized containers for each blueprint.
"""

import logging
import pickle
import random
from argparse import ArgumentParser, RawDescriptionHelpFormatter

import numpy as np

from blueprints.ecommerce_prototype import interface_blueprint
from constants import (
    BASE_LOGGER_NAME,
    HTML_OUTPUT_DIR,
    OPTIMIZATION_RESULTS_DIR,
    OUTPUT_DIR,
)
from logger import get_new_logger
from optimization.nsga3 import run_nsga3_optimization
from optimization.nsga3.result import print_result_overview
from rendering.renderer import HTMLRenderer
from scoring.constraints.min_size import MinSizeScorer
from scoring.constraints.padding import PaddingScorer
from util import container_optimization_results_to_optimized_containers

parser = ArgumentParser(
    prog="ui-nsga3",
    description=__doc__,
    formatter_class=RawDescriptionHelpFormatter,
)
parser.add_argument(
    "-g",
    "--generations",
    type=int,
    default=200,
    help="Number of generations to run optimization for",
)
parser.add_argument(
    "-p",
    "--min-pop-size",
    type=int,
    default=100,
    help="Minimum population size for optimization (will be used for reference direction generation, default: 100)",
)
parser.add_argument(
    "-s",
    "--seed",
    type=int,
    default=None,
    help="Random seed for optimization (default: None)",
)
parser.add_argument(
    "-c",
    "--collect-metrics",
    action="store_true",
    help="Whether to record optimization results to disk (default: False)",
)
parser.add_argument(
    "-v",
    "--video",
    action="store_true",
    help="Whether to render a video of the optimization process (default: False)",
)


def setup_logger(level: str = "INFO"):
    logger = logging.getLogger(BASE_LOGGER_NAME)
    logger.setLevel(level)

    if not logger.handlers:
        stream_handler = logging.StreamHandler()
        stream_handler.setLevel(level)
        stream_formatter = logging.Formatter("[%(levelname)s] [%(name)s] - %(message)s")
        stream_handler.setFormatter(stream_formatter)
        logger.addHandler(stream_handler)

    logger.propagate = False
    return logger


if __name__ == "__main__":
    args = parser.parse_args()

    args_text = f"""
Running optimization with the following parameters:
Generations:         \t{args.generations}
Min Population Size: \t{args.min_pop_size}
Seed:                \t{args.seed}
Collect Metrics:     \t{args.collect_metrics}
Render Video:        \t{args.video}
    """
    print(args_text)

    setup_logger("DEBUG")
    logger = get_new_logger("main")

    # Init output directories
    logger.info(
        f"Creating output directories: {HTML_OUTPUT_DIR}, {OPTIMIZATION_RESULTS_DIR}"
    )
    HTML_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    OPTIMIZATION_RESULTS_DIR.mkdir(parents=True, exist_ok=True)

    SEED = args.seed
    if SEED is not None:
        random.seed(SEED)
        np.random.seed(SEED)

    # Run optimization
    container_optimzation_results = run_nsga3_optimization(
        root_blueprint=interface_blueprint,
        n_gen=args.generations,
        min_pop_size=args.min_pop_size,
        seed=SEED,
        constraints=[
            PaddingScorer(padding=0.01),
            MinSizeScorer(min_width=0.0, min_height=0.0),
        ],
        mutation_rate=0.1,
        collect_metrics=args.collect_metrics,
    )

    if args.collect_metrics:
        pickle.dump(
            container_optimzation_results,
            open(OPTIMIZATION_RESULTS_DIR / "container_optimization_results.pkl", "wb"),
        )

    # Convert to optimized containers for easier rendering
    optimized_containers = container_optimization_results_to_optimized_containers(
        container_optimzation_results
    )

    # Assemble final ui
    logger.info("Writing assembled best UI to disk")
    optimized_root_container = optimized_containers[interface_blueprint.blueprint_id]
    HTMLRenderer.get_instance().write_container_to_html(
        optimized_root_container,
        HTML_OUTPUT_DIR / "final_optimized_ui.html",
        optimized_containers,
    )

    # Print scores
    print_result_overview(container_optimzation_results)

    if args.video:
        logger.info("Rendering generation progression video")
        # Render generation progression video
        HTMLRenderer.get_instance().render_generation_progression_video(
            interface_blueprint.blueprint_id,
            container_optimzation_results,
            OUTPUT_DIR / "generation_progression.mp4",
        )

    HTMLRenderer.close()

    logger.info("Done! All output written to disk.")
