"""
A framework for User Interface generation/optimization using NSGA-III (Non-dominated Sorting Genetic Algorithm III).
Uses a predefiend set of scorers/criteria and a blueprint of the Interface to generate approximately optimal UI designs.
The generated designs will be written as HTML files in the output directory.\n

Due to the complexity of the problem the Blueprint can be devided into sub-blueprints which will be optimized separately.
The algorithm will BFS through the blueprint hierarchy and optimize each blueprint separately.
At the end the final UI will be generated by combining the optimized containers for each blueprint.
"""

import logging
import random
from argparse import ArgumentParser, RawDescriptionHelpFormatter

import numpy as np

from constants import BASE_LOGGER_NAME, OUTPUT_DIR
from optimization.nsga3 import run_nsga3_optimization
from rendering.renderer import HTMLRenderer
from ui.structure import interface_blueprint

parser = ArgumentParser(
    prog="ui-nsga3",
    description=__doc__,
    formatter_class=RawDescriptionHelpFormatter,
)
parser.add_argument(
    "-g",
    "--generations",
    type=int,
    default=200,
    help="Number of generations to run optimization for",
)
parser.add_argument(
    "-p",
    "--min-pop-size",
    type=int,
    default=100,
    help="Minimum population size for optimization (will be used for reference direction generation, default: 100)",
)
parser.add_argument(
    "-s",
    "--seed",
    type=int,
    default=None,
    help="Random seed for optimization (default: None)",
)

parser.parse_args()


def setup_logger(level: str = "INFO"):
    stream_handler = logging.StreamHandler()
    stream_handler.setLevel(level)
    stream_formatter = logging.Formatter("[%(levelname)s] [%(name)s] - %(message)s")
    stream_handler.setFormatter(stream_formatter)

    logger = logging.getLogger(BASE_LOGGER_NAME)
    logger.setLevel(level)
    logger.addHandler(stream_handler)
    logger.propagate = False
    return logger


if __name__ == "__main__":
    setup_logger("DEBUG")

    args = parser.parse_args()
    SEED = args.seed
    if SEED is not None:
        random.seed(SEED)
        np.random.seed(SEED)

    # Run optimization
    optimized_containers = run_nsga3_optimization(
        root_blueprint=interface_blueprint,
        n_gen=args.generations,
        min_pop_size=args.min_pop_size,
        seed=SEED,
    )

    # Write optimized containers to HTML files
    OUTPUT_DIR.mkdir(exist_ok=True)
    for container in optimized_containers.values():
        HTMLRenderer.write_container_to_html(
            container, OUTPUT_DIR / f"{container.label}_optimized.html"
        )

    # Assemble final ui
    optimized_root_container = optimized_containers[interface_blueprint.blueprint_id]
    HTMLRenderer.write_container_to_html(
        optimized_root_container,
        OUTPUT_DIR / "final_optimized_ui.html",
        optimized_containers,
    )
